// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "iQOO Neo5_jin"
#define SECRET_PASS "hc3ju3wx"

// #define SECRET_SSID "bestIoT"
// #define SECRET_PASS "Q1w2e3r4t5y6u7,."

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "ae4xgftvpwfb4-ats.iot.eu-west-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICgjCCAWqgAwIBAgIUdkBKAztkL8LIiIfvhQQVHNRRiRcwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIzMDIyMjE0MzIx
MloXDTQ5MTIzMTIzNTk1OVowEjEQMA4GA1UEAxMHYmVzdElvVDBZMBMGByqGSM49
AgEGCCqGSM49AwEHA0IABB7whDh56PDmJrNHsnSXGVG2Uvyl+oSGfOaZVKvngXad
T7K2kXTqS43pKPOtTxJW8UMH7BXE52s9mhKMB+jR9WGjYDBeMB8GA1UdIwQYMBaA
FGIsIwDecdWTHHZYy8CPEI8iZmrfMB0GA1UdDgQWBBQ3J2VbPrBjycKyQQrvO2v5
goUFZDAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsF
AAOCAQEAMPU4BwIAzsSXTbBdGRL/PthHaIExurNo7V3fxZgVl1J59X5ow1770YKv
DRhTEeh0hUOjZls/wrF7mA/uGtTNKbIoGjeSBuSKyNC+PYZtLigKhovGbrDb15Je
QlhRImpYNAyUGn+ue8Mft4PqBOkfMU8k9nfLBuS5bgDgPp3KEQDOJPSp9JHR/i7q
b4kls0bAgoR9uLeK++Cpe21N4Uf9P7y5S/ReYvSOH5kDlniH822KtO9Snq3nKiqb
1824/reWb76QH6au6vTOAURRJpCl5pgInNBkYDUMmpMnAPP5yCdibczyeQZAMcmw
QbXzjBoQBfRLCVPm3aR4rH2f5HRBtg==
-----END CERTIFICATE-----
)";
